@baseUrl = http://localhost:8080
@apiAuth = {{baseUrl}}/api/v1/auth

### ! AJUSTA SEGUN CORRESPONDA 
@yourEndpoint = {{baseUrl}}/api/v1/contacts


# =====================================================================
# ?       ESTRUCTURA BASE PARA TESTEAR TUS ENDPOINTS CON TOKENSS
# =====================================================================

### 1. Login as USER (test@gmail.com)
# @name loginUser
POST {{apiAuth}}/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

### set token user
@userToken = {{loginUser.response.body.data.accessToken}}

### 1b. Login as ADMIN (admin@gmail.com)

# @name loginAdmin
POST {{apiAuth}}/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

### set token admin
@adminToken = {{loginAdmin.response.body.data.accessToken}}


# =====================================================================
#    ? TUS ENDPOINTS -
# =====================================================================

### 1. Create Contact - Success
# @name createContact
POST {{yourEndpoint}}
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
    "name": "Juan Pérez",
    "email": "juan.perez@example.com",
    "phone": "1123456789"
}


### 
GET {{yourEndpoint}}
Authorization: Bearer {{adminToken}}

